name: main

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  packages:
    name: test packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg:
        - anup
        - customscripts
        - mpd_discord_richpresence
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: natto1784
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#${{ matrix.pkg }}

  nixos:
    name: build nixos configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          #- Marisa
          #- Satori
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: natto1784
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
  home-manager:
    name: build home-manager configurations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        home:
          #- natto
        homeaarch:
          - ottan
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: natto1784
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu-latest
          run: nix build -L .#hm-configs.${{ matrix.homeaarch }}.activationPackage
     - run: nix build -L .#hm-configs.${{ matrix.home }}.activationPackage

